package:
  name: libpotrace
  version: 1.14.0

source:
  # http://potrace.sourceforge.net/download/1.14/potrace-1.14.tar.gz
  path: ../vendor/potrace-1.14

requirements:
  build:
    - gcc
    - libgfortran

  run:
    - openblas
    - python

about:
  home: https://www.potrace.org
  summary: "Does potracy stuffs"
  license: BSD
