package:
  name: gippy
  version: 1.0.0b8

source:
  # https://github.com/gipit/gippy/archive/develop.zip
  path: ../vendor/gippy
requirements:
  build:
    - gcc
    - python
    - numpy 1.12.0
    - libgdal 2.1.0
    - potrace 1.11

  run:
    - python
    - numpy 1.12.0
    - fiona 1.7.4 
    - jpeg
    - potrace 1.11

build:
  string: py{{py}}_0

about:
  home: https://github.com/gipit/gippy
  summary: "Does gippy stuffs"
  license: Apache 2.0
