package:
  name: gippy
  version: 1.0.0b8

source:
  path: ../vendor/gippy
requirements:
  build:
    - gcc
    - python
    - numpy 1.12.0
    - gdal 2.1.3

  run:
    - python
    - numpy 1.12.0
    - fiona 1.7.4 
    #- gdal 2.1.3
    - jpeg
    - potrace 1.11

build:
  string: py{{py}}_0

about:
  home: https://github.com/gipit/gippy
  summary: "Does gippy stuffs"
  license: Apache 2.0
