name: pzsvc-ndwi
channels:
  - Coastline
  - conda-forge
  - bioconda
  - defaults
dependencies:
- cython
- numpy
- potrace
#- python=2.7.13
- pip
- pypotrace
- libagg=2.5.0
- fiona=1.7.4
- gdal=2.1.3
- gippy
- beachfront
- bfalg-ndwi
- pzsvc-exec

