package:
  name: libagg
  version: 2.5.0

source:
  # http://www.antigrain.com/agg-2.5.tar.gz
  path: ../vendor/agg-2.5

requirements:
  build:
    - gcc
    - libgfortran

about:
  home: https://www.agg.org
  summary: "Does agg stuffs"
  license: BSD
