package:
  name: beachfront
  version: 0.1.0

source:
  # https://github.com/venicegeo/beachfront-py
  path: ../vendor/beachfront
requirements:
  build:
    - gcc
    - python
    - gippy
    - pypotrace
    - requests
    - fiona
    - pyproj
    - six

  run:
    - python
    - gippy
    - pypotrace
    - requests
    - fiona
    - pyproj
    - six

build:
  string: py{{py}}_0
  #binary_relocation: False

about:
  home: https://github.com/venicegeo/beachfront-py
  summary: "A library of functions used for the creation of vector shorelines automatically from imagery"
  license: Apache 2.0
